### ISSUE TITLE
LiveTelemetry.py line 157 

### ISSUE THREAD

**Issue by NetDriver0** [albertowd/live-telemetry#11]
![image](https://user-images.githubusercontent.com/59235207/178105023-679e0ae4-b373-4046-8a25-0789170a7941.png)

**Comment by albertowd** [comment]
Uhmmm, can you provide me more information?
Plugin version, was you using an older version before this one?
List of other loaded plugins.
Thanks

**Comment by NetDriver0** [comment]
Its newest version.
I tried older version after new one, but it dont work too.
I cant show all plugins right now, but as I remember I have this plugins:
dkLaptime, dkPedals, Sol apps, Drone Camera, proTyres, extMirrors(by CSP dev)

**Comment by albertowd** [comment]
So, if its a thing happening with wrong configuration, the newer version invalidates the conf.ini if there is a new version and resets itself, can you test it again?
I`ve also added fixes with missmoduling names.

**Comment by NetDriver0** [comment]
it works, thanks
